# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  build:
    docker:
      - image: circleci/node:9.9.0

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install --only=production

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Generate new matches
          # Only generate new matches if the phrase "generate" is in commit message.
          command: |
            last_commit="$(git log -1 --pretty=%B | cat | grep generate)"

            if [[ ${last_commit} == *[generate]* ]]
            then
              node public/js/generator.js
            fi

      - aws-s3/sync:
          from: public
          to: s3://kriskringle.andrewmadden.tech
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
